openapi: 3.0.3
info:
  title: KubSAU Test Backend Documentation
  description: Description here...
  termsOfService: noterms
  contact:
    email: no@thankyou.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.7
servers:
  - url: https://testbackend.melod1n.dedyn.io/openapi
tags:
  - name: authorization
    description: Всё, связанное с авторизацией
paths:
  /auth:
    get:
      tags:
        - authorization
      summary: Выдача id и токена по логину и паролю
      parameters:
        - name: login
          in: query
          description: Логин/почта
          required: true
          schema:
            type: string
        - name: password
          in: query
          description: Пароль
          required: true
          schema:
            type: string
      responses:
        '200':
          description: успешная выдача
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Auth'
components:
  schemas:
    Auth:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 1
          description: id пользователя
        accessToken:
          type: string
          description: токен
